version: 2

references:
  workspace: &workspace
    ~/hybid.sdk

  android_config: &android_config
    working_directory: *workspace

    docker:
      - image: pubnative/android:28_20190129

    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

    ## Cache
    gradle_key: &gradle_key
                  jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

    gems_key: &gems_key
                gems-{{ checksum "Gemfile.lock" }}

    restore_gradle_cache: &restore_gradle_cache
      restore_cache:
        key: *gradle_key

    restore_gems_cache: &restore_gems_cache
      restore_cache:
        key: *gems_key

    save_gradle_cache: &save_gradle_cache
      save_cache:
        key: *gradle_key
        paths:
          - ~/.gradle
          - ~/.m2

    save_gems_cache: &save_gems_cache
      save_cache:
        key: *gems_key
        paths:
          - vendor/bundle

      ## Dependencies
      ruby_dependencies: &ruby_dependencies
        run:
          name: Download Ruby Dependencies
          command: bundle check || bundle install --path vendor/bundle

      android_dependencies: &android_dependencies
        run:
          name: Download Android Dependencies
          command: ./gradlew androidDependencies

jobs:
  test_unit:
    <<: *android_config
    steps:
    - checkout
    - *restore_gradle_cache
    - *restore_gems_cache
    - *ruby_dependencies
    - *android_dependencies
    - *save_gradle_cache
    - *save_gems_cache
    - run:
        name: Run unit tests
        command: bundle exec fastlane unit_tests
    - store_artifacts:
        path: app/build/reports/
        destination: /reports/
    - store_test_results:
        path: app/build/test-results/
        destination: /test-results/

  deploy_crashlytics:
    <<: *android_config
    steps:
    - checkout
    - *restore_gradle_cache
    - *restore_gems_cache
    - *ruby_dependencies
    - *android_dependencies
    - *save_gradle_cache
    - *save_gems_cache
    - run:
        name: Deploy to Crashlytics Beta
        command: bundle exec fastlane deploy_to_crashlytics

workflows:
  version: 2
  workflow:
    jobs:
      - test_unit

      - deploy_crashlytics:
        filters:
          branches:
            only:
              - development-fix_circleci
        requires:
          - test_unit
