default_platform(:android)

platform :android do

    before_all do |lane, options|
        @build_type = "Debug"
        if not options.empty?
            @build_type = options["release"] ? "Release" : "Debug"
        end
    end

    desc "Runs all the tests"
    lane :unit_tests do
        gradle(task: "test")
    end

    desc "Runs Lint on the code"
        lane :lint_check do
            gradle(task: "lint")
        end

    desc "Submit a new Beta Build to Firebase App Distribution"
    lane :deploy_to_firebase do
        gradle(task: "clean assembleDebug")
        gradle(task: "clean appDistributionUploadDebug")
    end
end
