default_platform(:android)

platform :android do

    before_all do |lane, options|
        @build_type = "Debug"
        if not options.empty?
            @build_type = options["release"] ? "Release" : "Debug"
        end
    end

    desc "Runs all the tests"
    lane :unit_tests do
        gradle(task: "test")
    end

    desc "Submit a new Beta Build to Crashlytics Beta"
    lane :deploy_to_crashlytics do
        gradle(task: "clean assembleDebug")
        crashlytics
    end

    desc "Submit the HyBid SDK libs to Bintray"
        lane :publish_to_bintray do
            gradle(task: "clean assembleDebug bintrayUpload")
        end
end
