package net.pubnative.lite.sdk.models;

public class PNAdRequest extends AdRequest{
    public String os;
    public String osver;
    public String devicemodel;
    public String deviceHeight;
    public String deviceWidth;
    public String orientation;
    public String soundSetting;
    public String dnt;
    public String al;
    public String width;
    public String height;
    public String mf;
    public String af;
    public String locale;
    public String latitude;
    public String longitude;
    public String gender;
    public String age;
    public String bundleid;
    public String keywords;
    public String coppa;
    public String gid;
    public String gidmd5;
    public String gidsha1;
    public String testMode;
    public String displaymanager;
    public String displaymanagerver;
    public String omidpn;
    public String omidpv;
    public String usprivacy;
    public String userconsent;
    public String rv;
    public String protocol;
    public String api;
    public String impdepth;
    public String ageofapp;
    public String sessionduration;
}
